### ISSUE TITLE
Scripts to reproduce the baseline (M-SGD)

### ISSUE THREAD

**Issue by NormalUhr** [gaoliyao/Replica_Exchange_Stochastic_Gradient_MCMC#2]
Dear authors, would you please provide the scripts to reproduce your baseline, namely Resnet20s + CIFAR10/CIFAR100 with M-SGD and the results shown in Table 1 in the paper. Thanks.

**Comment by WayneDW** [comment]
Thanks for your interest to our paper.

By setting the temperature to 0 and running a single process instead of two processes as in the replica exchange method, you can easily reproduce the results via M-SGD, although we acknowledge right now the replica exchange method has two times of computational costs in these experiments.
